In [1]:
import numpy as np
import pandas as pd

In [2]:
laliga = pd.read_csv('Laliga.csv')

In [3]:
laliga.columns = laliga.iloc[0]

In [4]:
laliga.drop(laliga.index[0], inplace=True)
laliga.reset_index(level=0,inplace=True)
laliga

,index,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,...,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,1,Real Madrid,86,4385,2762,1647,552,563,5947,...,33,23,8,8,3,4,79,1929,1929,1
1,2,2,Barcelona,86,4262,2762,1581,573,608,5900,...,25,25,12,12,4,6,83,1929,1929,1
2,3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,...,10,8,16,9,7,6,56,1929,2002-03,1
3,4,4,Valencia,82,3386,2664,1187,616,861,4398,...,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,...,8,7,10,5,8,10,49,1929,1929,1
5,6,6,Sevilla,73,2819,2408,990,531,887,3680,...,1,4,4,5,12,6,32,1934-35,2001-02,1
6,7,7,Espanyol,82,2792,2626,948,608,1070,3609,...,-,-,4,5,2,5,16,1929,1994-95,3
7,8,8,Real Sociedad,70,2573,2302,864,577,861,3228,...,2,3,2,5,4,3,19,1929,2010-11,1
8,9,9,Zaragoza,58,2109,1986,698,522,766,2683,...,-,1,4,5,4,4,18,1939-40,2012-13,2
9,10,10,Real Betis,51,1884,1728,606,440,682,2159,...,1,-,2,3,4,4,14,1932-33,2015-16,1
10,11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,...,1,5,4,1,-,1,12,1941-42,2014-15,1
11,12,12,Celta Vigo,51,1789,1698,586,389,723,2278,...,-,-,-,2,4,5,11,1939-40,2012-13,4
12,13,13,Valladolid,42,1471,1466,463,384,619,1767,...,-,-,-,1,1,1,3,1948-49,2013-14,4
13,14,14,Racing Santander,44,1416,1428,453,336,639,1843,...,-,1,1,2,-,1,5,1929,2011-12,2
14,15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,...,-,1,1,2,2,1,7,1944-45,2015-16,2
15,16,16,Osasuna,37,1351,1318,426,327,565,1500,...,-,-,-,2,2,2,6,1935-36,2016-17,4
16,17,17,Malaga,36,1314,1255,390,330,535,1421,...,-,-,-,1,-,1,2,1949-50,2008-09,4
17,18,18,Oviedo,38,1174,1192,408,292,492,1642,...,-,-,3,2,2,4,11,1933-34,2000-01,3
18,19,19,Mallorca,27,1148,988,333,256,399,1182,...,-,-,2,-,2,1,5,1960-61,2012-13,3
19,20,20,Las Palmas,33,1020,1096,367,242,487,1347,...,-,1,1,1,1,1,5,1951-52,2015-16,2
20,21,21,Villarreal,17,970,646,266,172,208,892,...,-,1,1,2,3,2,9,1998-99,2013-14,2
21,22,22,Granada,23,667,742,218,175,349,819,...,-,-,-,-,-,2,2,1941-42,2016-17,6
22,23,23,Rayo Vallecano,17,662,652,189,148,305,760,...,-,-,-,-,-,-,-,1977-78,2015-16,8
23,24,24,Elche,21,606,678,203,180,295,750,...,-,-,-,-,1,1,2,1959-60,2014-15,5
24,25,25,Getafe,12,553,456,147,112,197,520,...,-,-,-,-,-,1,1,2004-05,2015-16,6
25,26,26,Hercules,20,538,628,184,149,295,716,...,-,-,-,-,1,4,5,1935-36,2010-11,5
26,27,27,Tenerife,13,510,494,155,128,211,619,...,-,-,-,-,2,-,2,1961-62,2009-10,5
27,28,28,Murcia,18,445,586,145,143,298,607,...,-,-,-,-,-,-,-,1940-41,2007-08,11
28,29,29,Alaves,12,421,380,125,81,174,458,...,-,-,-,-,-,1,1,1930-31,2016-17,6
29,30,30,Levante,11,416,402,113,95,194,430,...,-,-,-,-,-,1,1,1963-64,2015-16,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,32,Sabadell,14,353,426,129,95,202,492,...,-,-,-,1,1,-,2,1943-44,1987-88,4
32,33,33,Cadiz,12,343,448,104,127,217,393,...,-,-,-,-,-,-,-,1977-78,2005-06,12
33,34,34,Logrones,9,293,346,96,92,158,291,...,-,-,-,-,-,-,-,1987-88,1996-97,7
34,35,35,Castellon,11,285,334,103,79,152,419,...,-,-,-,1,2,-,3,1941-42,1990-91,4
35,36,36,Albacete,7,277,270,76,76,118,320,...,-,-,-,-,-,-,-,1991-92,2004-05,7
36,37,37,Almeria,6,242,228,62,56,110,244,...,-,-,-,-,-,-,-,2007-08,2014-15,8
37,38,38,Cordoba,9,230,282,82,63,137,285,...,-,-,-,-,1,-,1,1962-63,2014-15,5
38,39,39,Compostela,4,190,160,52,45,63,199,...,-,-,-,-,-,-,-,1994-95,1997-98,10
39,40,40,Recreativo,5,188,186,50,46,90,202,...,-,-,-,-,-,-,-,1978-79,2008-09,8
40,41,41,Burgos CF,6,168,204,59,50,95,216,...,-,-,-,-,-,-,-,1971-72,1979-80,12
41,42,42,Pontevedra,6,150,180,53,44,83,165,...,-,-,-,-,-,-,-,1963-64,1969-70,7
42,43,43,Numancia,4,148,152,37,37,78,155,...,-,-,-,-,-,-,-,1999-00,2008-09,17
43,44,44,Eibar,3,132,114,35,27,52,139,...,-,-,-,-,-,-,-,2014-15,2014-15,10
44,45,45,Arenas,7,107,130,43,21,66,227,...,-,-,1,-,3,-,4,1929,1934-35,3
45,46,46,Real Burgos,3,96,114,26,44,44,101,...,-,-,-,-,-,-,-,1990-91,1992-93,9
46,47,47,Gimnastic,4,91,116,34,16,66,181,...,-,-,-,-,-,-,-,1947-48,2006-07,7
47,48,48,Extremadura,2,83,80,20,23,37,62,...,-,-,-,-,-,-,-,1996-97,1998-99,17
48,49,49,Merida,2,81,80,19,24,37,70,...,-,-,-,-,-,-,-,1995-96,1997-98,19
49,50,50,Alcoyano,4,76,108,30,16,62,145,...,-,-,-,-,-,-,-,1945-46,1950-51,10
50,51,51,Jaen,3,71,90,29,13,48,121,...,-,-,-,-,-,-,-,1953-54,1957-58,14
51,52,52,Real Union,4,56,72,21,14,37,153,...,-,-,-,-,-,1,1,1929,1931-32,6
52,53,53,AD Almeria,2,52,68,17,18,33,71,...,-,-,-,-,-,-,-,1979-80,1980-81,10
53,54,54,Europa,3,42,54,18,6,30,97,...,-,-,-,-,-,-,-,1929,1930-31,8
54,55,55,Lleida,2,40,68,13,14,41,70,...,-,-,-,-,-,-,-,1950-51,1993-94,16
55,56,56,Leganes,1,35,38,8,11,19,36,...,-,-,-,-,-,-,-,2016-17,2016-17,17
56,57,57,Xerez,1,34,38,8,10,20,38,...,-,-,-,-,-,-,-,2009-10,2009-10,20
57,58,58,Condal,1,22,30,7,8,15,37,...,-,-,-,-,-,-,-,1956-57,1956-57,16
58,59,59,Atletico Tetuan,1,19,30,7,5,18,51,...,-,-,-,-,-,-,-,1951-52,1951-52,16
59,60,60,Cultural Leonesa,1,14,30,5,4,21,34,...,-,-,-,-,-,-,-,1955-56,1955-56,15
60,61,61,Girona,1,-,-,-,-,-,-,...,-,-,-,-,-,-,-,2017-18,2017-18,9

In [5]:
laliga.replace(
    to_replace=['-'],
    value='0',
    inplace=True
)

In [6]:
laliga

,index,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,...,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,1,Real Madrid,86,4385,2762,1647,552,563,5947,...,33,23,8,8,3,4,79,1929,1929,1
1,2,2,Barcelona,86,4262,2762,1581,573,608,5900,...,25,25,12,12,4,6,83,1929,1929,1
2,3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,...,10,8,16,9,7,6,56,1929,2002-03,1
3,4,4,Valencia,82,3386,2664,1187,616,861,4398,...,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,...,8,7,10,5,8,10,49,1929,1929,1
5,6,6,Sevilla,73,2819,2408,990,531,887,3680,...,1,4,4,5,12,6,32,1934-35,2001-02,1
6,7,7,Espanyol,82,2792,2626,948,608,1070,3609,...,0,0,4,5,2,5,16,1929,1994-95,3
7,8,8,Real Sociedad,70,2573,2302,864,577,861,3228,...,2,3,2,5,4,3,19,1929,2010-11,1
8,9,9,Zaragoza,58,2109,1986,698,522,766,2683,...,0,1,4,5,4,4,18,1939-40,2012-13,2
9,10,10,Real Betis,51,1884,1728,606,440,682,2159,...,1,0,2,3,4,4,14,1932-33,2015-16,1
10,11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,...,1,5,4,1,0,1,12,1941-42,2014-15,1
11,12,12,Celta Vigo,51,1789,1698,586,389,723,2278,...,0,0,0,2,4,5,11,1939-40,2012-13,4
12,13,13,Valladolid,42,1471,1466,463,384,619,1767,...,0,0,0,1,1,1,3,1948-49,2013-14,4
13,14,14,Racing Santander,44,1416,1428,453,336,639,1843,...,0,1,1,2,0,1,5,1929,2011-12,2
14,15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,...,0,1,1,2,2,1,7,1944-45,2015-16,2
15,16,16,Osasuna,37,1351,1318,426,327,565,1500,...,0,0,0,2,2,2,6,1935-36,2016-17,4
16,17,17,Malaga,36,1314,1255,390,330,535,1421,...,0,0,0,1,0,1,2,1949-50,2008-09,4
17,18,18,Oviedo,38,1174,1192,408,292,492,1642,...,0,0,3,2,2,4,11,1933-34,2000-01,3
18,19,19,Mallorca,27,1148,988,333,256,399,1182,...,0,0,2,0,2,1,5,1960-61,2012-13,3
19,20,20,Las Palmas,33,1020,1096,367,242,487,1347,...,0,1,1,1,1,1,5,1951-52,2015-16,2
20,21,21,Villarreal,17,970,646,266,172,208,892,...,0,1,1,2,3,2,9,1998-99,2013-14,2
21,22,22,Granada,23,667,742,218,175,349,819,...,0,0,0,0,0,2,2,1941-42,2016-17,6
22,23,23,Rayo Vallecano,17,662,652,189,148,305,760,...,0,0,0,0,0,0,0,1977-78,2015-16,8
23,24,24,Elche,21,606,678,203,180,295,750,...,0,0,0,0,1,1,2,1959-60,2014-15,5
24,25,25,Getafe,12,553,456,147,112,197,520,...,0,0,0,0,0,1,1,2004-05,2015-16,6
25,26,26,Hercules,20,538,628,184,149,295,716,...,0,0,0,0,1,4,5,1935-36,2010-11,5
26,27,27,Tenerife,13,510,494,155,128,211,619,...,0,0,0,0,2,0,2,1961-62,2009-10,5
27,28,28,Murcia,18,445,586,145,143,298,607,...,0,0,0,0,0,0,0,1940-41,2007-08,11
28,29,29,Alaves,12,421,380,125,81,174,458,...,0,0,0,0,0,1,1,1930-31,2016-17,6
29,30,30,Levante,11,416,402,113,95,194,430,...,0,0,0,0,0,1,1,1963-64,2015-16,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,32,Sabadell,14,353,426,129,95,202,492,...,0,0,0,1,1,0,2,1943-44,1987-88,4
32,33,33,Cadiz,12,343,448,104,127,217,393,...,0,0,0,0,0,0,0,1977-78,2005-06,12
33,34,34,Logrones,9,293,346,96,92,158,291,...,0,0,0,0,0,0,0,1987-88,1996-97,7
34,35,35,Castellon,11,285,334,103,79,152,419,...,0,0,0,1,2,0,3,1941-42,1990-91,4
35,36,36,Albacete,7,277,270,76,76,118,320,...,0,0,0,0,0,0,0,1991-92,2004-05,7
36,37,37,Almeria,6,242,228,62,56,110,244,...,0,0,0,0,0,0,0,2007-08,2014-15,8
37,38,38,Cordoba,9,230,282,82,63,137,285,...,0,0,0,0,1,0,1,1962-63,2014-15,5
38,39,39,Compostela,4,190,160,52,45,63,199,...,0,0,0,0,0,0,0,1994-95,1997-98,10
39,40,40,Recreativo,5,188,186,50,46,90,202,...,0,0,0,0,0,0,0,1978-79,2008-09,8
40,41,41,Burgos CF,6,168,204,59,50,95,216,...,0,0,0,0,0,0,0,1971-72,1979-80,12
41,42,42,Pontevedra,6,150,180,53,44,83,165,...,0,0,0,0,0,0,0,1963-64,1969-70,7
42,43,43,Numancia,4,148,152,37,37,78,155,...,0,0,0,0,0,0,0,1999-00,2008-09,17
43,44,44,Eibar,3,132,114,35,27,52,139,...,0,0,0,0,0,0,0,2014-15,2014-15,10
44,45,45,Arenas,7,107,130,43,21,66,227,...,0,0,1,0,3,0,4,1929,1934-35,3
45,46,46,Real Burgos,3,96,114,26,44,44,101,...,0,0,0,0,0,0,0,1990-91,1992-93,9
46,47,47,Gimnastic,4,91,116,34,16,66,181,...,0,0,0,0,0,0,0,1947-48,2006-07,7
47,48,48,Extremadura,2,83,80,20,23,37,62,...,0,0,0,0,0,0,0,1996-97,1998-99,17
48,49,49,Merida,2,81,80,19,24,37,70,...,0,0,0,0,0,0,0,1995-96,1997-98,19
49,50,50,Alcoyano,4,76,108,30,16,62,145,...,0,0,0,0,0,0,0,1945-46,1950-51,10
50,51,51,Jaen,3,71,90,29,13,48,121,...,0,0,0,0,0,0,0,1953-54,1957-58,14
51,52,52,Real Union,4,56,72,21,14,37,153,...,0,0,0,0,0,1,1,1929,1931-32,6
52,53,53,AD Almeria,2,52,68,17,18,33,71,...,0,0,0,0,0,0,0,1979-80,1980-81,10
53,54,54,Europa,3,42,54,18,6,30,97,...,0,0,0,0,0,0,0,1929,1930-31,8
54,55,55,Lleida,2,40,68,13,14,41,70,...,0,0,0,0,0,0,0,1950-51,1993-94,16
55,56,56,Leganes,1,35,38,8,11,19,36,...,0,0,0,0,0,0,0,2016-17,2016-17,17
56,57,57,Xerez,1,34,38,8,10,20,38,...,0,0,0,0,0,0,0,2009-10,2009-10,20
57,58,58,Condal,1,22,30,7,8,15,37,...,0,0,0,0,0,0,0,1956-57,1956-57,16
58,59,59,Atletico Tetuan,1,19,30,7,5,18,51,...,0,0,0,0,0,0,0,1951-52,1951-52,16
59,60,60,Cultural Leonesa,1,14,30,5,4,21,34,...,0,0,0,0,0,0,0,1955-56,1955-56,15
60,61,61,Girona,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2017-18,2017-18,9

In [7]:
Debut1 = ((laliga['Debut']>='1930')&(laliga['Debut']<='1980'))

In [8]:
Team1 = laliga[((laliga['Debut']>='1930')&(laliga['Debut']<='1980'))]
print("The teams which have started playing from 1930 to 1980 are as follows:")
Team1['Team']

The teams which have started playing from 1930 to 1980 are as follows:

3                Valencia
5                 Sevilla
8                Zaragoza
9              Real Betis
10    Deportivo La Coruna
11             Celta Vigo
12             Valladolid
14         Sporting Gijon
15                Osasuna
16                 Malaga
17                 Oviedo
18               Mallorca
19             Las Palmas
21                Granada
22         Rayo Vallecano
23                  Elche
25               Hercules
26               Tenerife
27                 Murcia
28                 Alaves
29                Levante
30              Salamanca
31               Sabadell
32                  Cadiz
34              Castellon
37                Cordoba
39             Recreativo
40              Burgos CF
41             Pontevedra
46              Gimnastic
49               Alcoyano
50                   Jaen
52             AD Almeria
54                 Lleida
57                 Condal
58        Atletico Tetuan
59       Cultural Leonesa
Name: Team, dtype: object

In [9]:
laliga['Points'].astype(str).astype(int).nlargest(5)

0    4385
1    4262
2    3442
3    3386
4    3368
Name: Points, dtype: int64

In [10]:
indexp = laliga['Points'].astype(str).astype(int).nlargest(5).index
indexp

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [11]:
print("The top 5 teams with higest points are as follows:")
Top5 = laliga.iloc[indexp]
Top5['Team']

The top 5 teams with higest points are as follows:

0        Real Madrid
1          Barcelona
2    Atletico Madrid
3           Valencia
4    Athletic Bilbao
Name: Team, dtype: object

In [12]:
def Goal_diff_count(Teams):
    return int(Teams[1])-int(Teams[2])

GoalDiff = laliga[['Team','GoalsFor','GoalsAgainst']].apply(lambda x: Goal_diff_count(x),axis=1)

In [13]:
print("The teams and their goal differences are as follows:")
for x in range(GoalDiff.count()):
    print(laliga.loc[x,'Team']+" goaldiff is "+str(GoalDiff[x]))

The teams and their goal differences are as follows:
Real Madrid goaldiff is 2807
Barcelona goaldiff is 2786
Atletico Madrid goaldiff is 1225
Valencia goaldiff is 929
Athletic Bilbao goaldiff is 931
Sevilla goaldiff is 307
Espanyol goaldiff is -280
Real Sociedad goaldiff is -2
Zaragoza goaldiff is -164
Real Betis goaldiff is -333
Deportivo La Coruna goaldiff is -136
Celta Vigo goaldiff is -346
Valladolid goaldiff is -413
Racing Santander goaldiff is -525
Sporting Gijon goaldiff is -399
Osasuna goaldiff is -334
Malaga goaldiff is -342
Oviedo goaldiff is -309
Mallorca goaldiff is -189
Las Palmas goaldiff is -399
Villarreal goaldiff is 103
Granada goaldiff is -338
Rayo Vallecano goaldiff is -328
Elche goaldiff is -272
Getafe goaldiff is -113
Hercules goaldiff is -334
Tenerife goaldiff is -125
Murcia goaldiff is -385
Alaves goaldiff is -165
Levante goaldiff is -202
Salamanca goaldiff is -159
Sabadell goaldiff is -228
Cadiz goaldiff is -269
Logrones goaldiff is -198
Castellon goaldiff is -169
Albacete goaldiff is -90
Almeria goaldiff is -122
Cordoba goaldiff is -145
Compostela goaldiff is -42
Recreativo goaldiff is -94
Burgos CF goaldiff is -94
Pontevedra goaldiff is -56
Numancia goaldiff is -98
Eibar goaldiff is -28
Arenas goaldiff is -81
Real Burgos goaldiff is -38
Gimnastic goaldiff is -114
Extremadura goaldiff is -55
Merida goaldiff is -45
Alcoyano goaldiff is -107
Jaen goaldiff is -62
Real Union goaldiff is -31
AD Almeria goaldiff is -45
Europa goaldiff is -34
Lleida goaldiff is -112
Leganes goaldiff is -19
Xerez goaldiff is -28
Condal goaldiff is -20
Atletico Tetuan goaldiff is -34
Cultural Leonesa goaldiff is -31
Girona goaldiff is 0

In [14]:
MinGD = GoalDiff[0:60].min()
MaxGD = GoalDiff[0:60].max()

In [15]:
MinIN=GoalDiff[GoalDiff==MinGD].index
MaxIN=GoalDiff[GoalDiff==MaxGD].index

In [16]:
print(laliga.loc[MinIN,'Team'])
print(laliga.loc[MaxIN,'Team'])

13    Racing Santander
Name: Team, dtype: object
0    Real Madrid
Name: Team, dtype: object

In [17]:
def Win_Percent(P):
    if int(P[1])!=0:
        return int(P[0])/int(P[1])
    else:
        return 0
laliga['Winning Percent'] = laliga[['GamesWon','GamesPlayed']].apply(lambda x: Win_Percent(x),axis=1)

In [18]:
laliga

,index,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,...,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Winning Percent
0,1,1,Real Madrid,86,4385,2762,1647,552,563,5947,...,23,8,8,3,4,79,1929,1929,1,0.596307
1,2,2,Barcelona,86,4262,2762,1581,573,608,5900,...,25,12,12,4,6,83,1929,1929,1,0.572411
2,3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,...,8,16,9,7,6,56,1929,2002-03,1,0.474751
3,4,4,Valencia,82,3386,2664,1187,616,861,4398,...,6,10,11,10,7,50,1931-32,1987-88,1,0.445571
4,5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,...,7,10,5,8,10,49,1929,1929,1,0.437726
5,6,6,Sevilla,73,2819,2408,990,531,887,3680,...,4,4,5,12,6,32,1934-35,2001-02,1,0.411130
6,7,7,Espanyol,82,2792,2626,948,608,1070,3609,...,0,4,5,2,5,16,1929,1994-95,3,0.361005
7,8,8,Real Sociedad,70,2573,2302,864,577,861,3228,...,3,2,5,4,3,19,1929,2010-11,1,0.375326
8,9,9,Zaragoza,58,2109,1986,698,522,766,2683,...,1,4,5,4,4,18,1939-40,2012-13,2,0.351460
9,10,10,Real Betis,51,1884,1728,606,440,682,2159,...,0,2,3,4,4,14,1932-33,2015-16,1,0.350694
10,11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,...,5,4,1,0,1,12,1941-42,2014-15,1,0.367974
11,12,12,Celta Vigo,51,1789,1698,586,389,723,2278,...,0,0,2,4,5,11,1939-40,2012-13,4,0.345112
12,13,13,Valladolid,42,1471,1466,463,384,619,1767,...,0,0,1,1,1,3,1948-49,2013-14,4,0.315825
13,14,14,Racing Santander,44,1416,1428,453,336,639,1843,...,1,1,2,0,1,5,1929,2011-12,2,0.317227
14,15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,...,1,1,2,2,1,7,1944-45,2015-16,2,0.323045
15,16,16,Osasuna,37,1351,1318,426,327,565,1500,...,0,0,2,2,2,6,1935-36,2016-17,4,0.323217
16,17,17,Malaga,36,1314,1255,390,330,535,1421,...,0,0,1,0,1,2,1949-50,2008-09,4,0.310757
17,18,18,Oviedo,38,1174,1192,408,292,492,1642,...,0,3,2,2,4,11,1933-34,2000-01,3,0.342282
18,19,19,Mallorca,27,1148,988,333,256,399,1182,...,0,2,0,2,1,5,1960-61,2012-13,3,0.337045
19,20,20,Las Palmas,33,1020,1096,367,242,487,1347,...,1,1,1,1,1,5,1951-52,2015-16,2,0.334854
20,21,21,Villarreal,17,970,646,266,172,208,892,...,1,1,2,3,2,9,1998-99,2013-14,2,0.411765
21,22,22,Granada,23,667,742,218,175,349,819,...,0,0,0,0,2,2,1941-42,2016-17,6,0.293801
22,23,23,Rayo Vallecano,17,662,652,189,148,305,760,...,0,0,0,0,0,0,1977-78,2015-16,8,0.289877
23,24,24,Elche,21,606,678,203,180,295,750,...,0,0,0,1,1,2,1959-60,2014-15,5,0.299410
24,25,25,Getafe,12,553,456,147,112,197,520,...,0,0,0,0,1,1,2004-05,2015-16,6,0.322368
25,26,26,Hercules,20,538,628,184,149,295,716,...,0,0,0,1,4,5,1935-36,2010-11,5,0.292994
26,27,27,Tenerife,13,510,494,155,128,211,619,...,0,0,0,2,0,2,1961-62,2009-10,5,0.313765
27,28,28,Murcia,18,445,586,145,143,298,607,...,0,0,0,0,0,0,1940-41,2007-08,11,0.247440
28,29,29,Alaves,12,421,380,125,81,174,458,...,0,0,0,0,1,1,1930-31,2016-17,6,0.328947
29,30,30,Levante,11,416,402,113,95,194,430,...,0,0,0,0,1,1,1963-64,2015-16,6,0.281095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,32,Sabadell,14,353,426,129,95,202,492,...,0,0,1,1,0,2,1943-44,1987-88,4,0.302817
32,33,33,Cadiz,12,343,448,104,127,217,393,...,0,0,0,0,0,0,1977-78,2005-06,12,0.232143
33,34,34,Logrones,9,293,346,96,92,158,291,...,0,0,0,0,0,0,1987-88,1996-97,7,0.277457
34,35,35,Castellon,11,285,334,103,79,152,419,...,0,0,1,2,0,3,1941-42,1990-91,4,0.308383
35,36,36,Albacete,7,277,270,76,76,118,320,...,0,0,0,0,0,0,1991-92,2004-05,7,0.281481
36,37,37,Almeria,6,242,228,62,56,110,244,...,0,0,0,0,0,0,2007-08,2014-15,8,0.271930
37,38,38,Cordoba,9,230,282,82,63,137,285,...,0,0,0,1,0,1,1962-63,2014-15,5,0.290780
38,39,39,Compostela,4,190,160,52,45,63,199,...,0,0,0,0,0,0,1994-95,1997-98,10,0.325000
39,40,40,Recreativo,5,188,186,50,46,90,202,...,0,0,0,0,0,0,1978-79,2008-09,8,0.268817
40,41,41,Burgos CF,6,168,204,59,50,95,216,...,0,0,0,0,0,0,1971-72,1979-80,12,0.289216
41,42,42,Pontevedra,6,150,180,53,44,83,165,...,0,0,0,0,0,0,1963-64,1969-70,7,0.294444
42,43,43,Numancia,4,148,152,37,37,78,155,...,0,0,0,0,0,0,1999-00,2008-09,17,0.243421
43,44,44,Eibar,3,132,114,35,27,52,139,...,0,0,0,0,0,0,2014-15,2014-15,10,0.307018
44,45,45,Arenas,7,107,130,43,21,66,227,...,0,1,0,3,0,4,1929,1934-35,3,0.330769
45,46,46,Real Burgos,3,96,114,26,44,44,101,...,0,0,0,0,0,0,1990-91,1992-93,9,0.228070
46,47,47,Gimnastic,4,91,116,34,16,66,181,...,0,0,0,0,0,0,1947-48,2006-07,7,0.293103
47,48,48,Extremadura,2,83,80,20,23,37,62,...,0,0,0,0,0,0,1996-97,1998-99,17,0.250000
48,49,49,Merida,2,81,80,19,24,37,70,...,0,0,0,0,0,0,1995-96,1997-98,19,0.237500
49,50,50,Alcoyano,4,76,108,30,16,62,145,...,0,0,0,0,0,0,1945-46,1950-51,10,0.277778
50,51,51,Jaen,3,71,90,29,13,48,121,...,0,0,0,0,0,0,1953-54,1957-58,14,0.322222
51,52,52,Real Union,4,56,72,21,14,37,153,...,0,0,0,0,1,1,1929,1931-32,6,0.291667
52,53,53,AD Almeria,2,52,68,17,18,33,71,...,0,0,0,0,0,0,1979-80,1980-81,10,0.250000
53,54,54,Europa,3,42,54,18,6,30,97,...,0,0,0,0,0,0,1929,1930-31,8,0.333333
54,55,55,Lleida,2,40,68,13,14,41,70,...,0,0,0,0,0,0,1950-51,1993-94,16,0.191176
55,56,56,Leganes,1,35,38,8,11,19,36,...,0,0,0,0,0,0,2016-17,2016-17,17,0.210526
56,57,57,Xerez,1,34,38,8,10,20,38,...,0,0,0,0,0,0,2009-10,2009-10,20,0.210526
57,58,58,Condal,1,22,30,7,8,15,37,...,0,0,0,0,0,0,1956-57,1956-57,16,0.233333
58,59,59,Atletico Tetuan,1,19,30,7,5,18,51,...,0,0,0,0,0,0,1951-52,1951-52,16,0.233333
59,60,60,Cultural Leonesa,1,14,30,5,4,21,34,...,0,0,0,0,0,0,1955-56,1955-56,15,0.166667
60,61,61,Girona,1,0,0,0,0,0,0,...,0,0,0,0,0,0,2017-18,2017-18,9,0.000000

In [19]:
indexpr = laliga['Winning Percent'].astype(str).astype(float).nlargest(5).index
indexpr

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [20]:
print("The top 5 teams with higest points are as follows:")
Top5 = laliga.iloc[indexpr]
Top5['Team']

The top 5 teams with higest points are as follows:

0        Real Madrid
1          Barcelona
2    Atletico Madrid
3           Valencia
4    Athletic Bilbao
Name: Team, dtype: object

In [21]:
#laliga.groupby(['BestPosition'])['Points'].sum()

In [22]:
laliga['Points']=pd.to_numeric(laliga.Points)
laliga.groupby(['BestPosition'])['Points'].sum()

BestPosition
1     27933
10      450
11      445
12      511
14       71
15       14
16       81
17      266
19       81
2      6904
20       34
3      5221
4      6563
5      1884
6      2113
7      1186
8      1134
9        96
Name: Points, dtype: int64